config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do
    resources :restaurants do
      resources :reviews, only: [ :index, :new, :create ]
    end
    resources :reviews, only: [ :show, :edit, :update, :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index 
        @restaurant = Restaurant.all
    end
    def show
    @restaurant = Restaurant.find(params[:id])
    end

    def new
        @restaurant = Restaurant.new
    end
    def create
        @restaurant = Restaurant.new(restaurant_params)
        @restaurant.save
        redirect_to restaurant_path(@restaurant)
    end

end






private

def find_restaurant
  @restaurant = Restaurant.find(params[:id])
end

def restaurant_params
    params.require(:restaurant).permit(:name,:adress,:phone_number,:category)
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
    def new
        # we need @restaurant in our `simple_form_for`
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new
      end
      def create
        @review = Review.new(review_params)
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review.restaurant = @restaurant
        if @review.save
          redirect_to restaurant_path(@restaurant)
        else
          render :new
        end
      end

private
def review_params
    params.require(:review).permit(:content)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        # we need @restaurant in our `simple_form_for`
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new
    end
    def create
      @review = Review.new(review_params)
      @restaurant = Restaurant.find(params[:restaurant_id])
      @review.restaurant = @restaurant
      if @review.save
        redirect_to restaurant_path(@restaurant)
      else
        render :new
      end
      def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to review_path(@review.restaurant)
    end
end
    

private
def review_params
    params.require(:review).permit(:content)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class = container>
  
    <h1>All Restaurants</h1>
  
    <ul>
    <% @restaurant.each do |restaurant| %>
    <li><%=link_to restaurant.name , restaurant_path(restaurant)  %></li>
    <% end %>
  </ul>
    <%=link_to "Add new Restaurant" , new_restaurant_path(@restaurant)%>
</div>

app/views/restaurants/new.html.erb
<div class = container >
<%= form_for Restaurant.new  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :adress   %>
  <%= f.text_field :adress %>
  <%= f.label :phone_number %>
  <%= f.number_field :phone_number %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div class = container>


<h2>Restaurant name : <%= @restaurant.name %></h2>
<p>Phone number : <%= @restaurant.phone_number %></p>
<p>Category :  <%= @restaurant.category %></p>



<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

<h5>Reviews</h5>
<ul class = "list_group">
<% @restaurant.reviews.each do |review|%>
<li class = "list-group-item"><%=review.content%>
 <li class="list-group-item">
      <%= review.content %>
      <%= link_to "Remove",
                  review_path(review),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </li>
</li> 
<%end%>
 



</div>

app/views/review/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<div class = "container">
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>